<a href="https://colab.research.google.com/github/taleksandrzak/ML-Bootcamp/blob/main/01_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn
Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  

Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn
```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```
Kurs stworzony w oparciu o wersję `0.22.1`

### Preprocessing danych:
1. [Import bibliotek](#0)
2. [Wygenerowanie danych](#1)
3. [Utworzenie kopii danych](#2)
4. [Zmiana typu danych i wstępna eksploracja](#3)
5. [LabelEncoder](#4)
6. [OneHotEncoder](#5)
7. [Pandas *get_dummies()*](#6)
8. [Standaryzacja - StandardScaler](#7)
9. [Przygotowanie danych do modelu](#8)

### <a name='0'></a> Import bibliotek

In [ ]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.1'

### <a name='1'></a> Wygenerowanie danych

In [ ]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw

  size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

### <a name='2'></a> Utworzenie kopii danych

In [ ]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      object
 1   color   5 non-null      object
 2   gender  5 non-null      object
 3   price   5 non-null      float64
 4   weight  5 non-null      int64
 5   bought  5 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes

### <a name='3'></a> Zmiana typu danych i wstępna eksploracja

In [ ]:
for col in ['size', 'color', 'gender', 'bought']:
    df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64
 4   weight  5 non-null      float64
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 744.0 bytes

In [ ]:
df.describe()

            price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [ ]:
df.describe().T

        count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [ ]:
df.describe(include=['category']).T

       count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [ ]:
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

### <a name='4'></a> LabelEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [ ]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [ ]:
le.classes_

array(['no', 'yes'], dtype=object)

In [ ]:
df['bought'] = le.fit_transform(df['bought'])
df

  size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [ ]:
le.inverse_transform(df['bought'])

array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

In [ ]:
df['bought'] = le.inverse_transform(df['bought'])
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

### <a name='5'></a> OneHotEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(df[['size']])

OneHotEncoder(sparse_output=False)

In [16]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [17]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [19]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [ ]:
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

### <a name='6'></a> Pandas *get_dummies()*

In [20]:
pd.get_dummies(data=df)

,price,weight,size_L,size_M,size_XL,color_blue,color_green,color_red,gender_female,gender_male,bought_no,bought_yes
0,199.0,500.0,False,False,True,False,False,True,True,False,False,True
1,89.0,450.0,True,False,False,False,True,False,False,True,True,False
2,99.0,300.0,False,True,False,True,False,False,False,True,False,True
3,129.0,380.0,True,False,False,False,True,False,True,False,True,False
4,79.0,410.0,False,True,False,False,False,True,True,False,False,True

In [21]:
pd.get_dummies(data=df, drop_first=True)

,price,weight,size_M,size_XL,color_green,color_red,gender_male,bought_yes
0,199.0,500.0,False,True,False,True,False,True
1,89.0,450.0,False,False,True,False,True,False
2,99.0,300.0,True,False,False,False,True,True
3,129.0,380.0,False,False,True,False,False,False
4,79.0,410.0,True,False,False,True,False,True

In [22]:
pd.get_dummies(data=df, drop_first=True, prefix='new')

   price  weight  new_M  new_XL  new_green  new_red  new_male  new_yes
0  199.0   500.0  False    True      False     True     False     True
1   89.0   450.0  False   False       True    False      True    False
2   99.0   300.0   True   False      False    False      True     True
3  129.0   380.0  False   False       True    False     False    False
4   79.0   410.0   True   False      False     True     False     True

In [23]:
pd.get_dummies(data=df, drop_first=True, prefix_sep='-', prefix='new')

   price  weight  new-M  new-XL  new-green  new-red  new-male  new-yes
0  199.0   500.0  False    True      False     True     False     True
1   89.0   450.0  False   False       True    False      True    False
2   99.0   300.0   True   False      False    False      True     True
3  129.0   380.0  False   False       True    False     False    False
4   79.0   410.0   True   False      False     True     False     True

In [24]:
pd.get_dummies(data=df, drop_first=True, columns=['size'])

   color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0   500.0    yes   False     True
1  green    male   89.0   450.0     no   False    False
2   blue    male   99.0   300.0    yes    True    False
3  green  female  129.0   380.0     no   False    False
4    red  female   79.0   410.0    yes    True    False

### <a name='7'></a> Standaryzacja - StandardScaler

std() - pandas nieobciążony  
std() - numpy obciążony

In [ ]:
print(f"{df['price']}\n")
print(f"Średnia: {df['price'].mean()}")
print(f"Odchylenie standardowe: {df['price'].std():.4f}")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średnia: 119.0
Odchylenie standardowe: 48.4768

In [ ]:
(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [ ]:
def standardize(x):
    return (x - x.mean()) / x.std()

standardize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [ ]:
from sklearn.preprocessing import scale

scale(df['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df[['price']])
scaler.transform(df[['price']])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [26]:
scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])
df

  size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

### <a name='8'></a> Przygotowanie danych do modelu

In [27]:
df = df_raw.copy()
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [28]:
le = LabelEncoder()

df['bought'] = le.fit_transform(df['bought'])

scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

df = pd.get_dummies(data=df, drop_first=True)
df

,price,weight,bought,size_M,size_XL,color_green,color_red,gender_male
0,1.845062,1.366002,1,False,True,False,True,False
1,-0.691898,0.623610,0,False,False,True,False,True
2,-0.461266,-1.603567,1,True,False,False,False,True
3,0.230633,-0.415740,0,False,False,True,False,False
4,-0.922531,0.029696,1,True,False,False,True,False